version: '3'

networks:
  app:

services:
  web:
    image: node
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - app
#    command: sh -c "npm install && npx lerna run web:build && npx lerna run web:start"
    command: sh -c "npm install && npx lerna run web:dev"
    working_dir: /app
    volumes:
      - ../:/app
    restart: unless-stopped

  server:
    image: node
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - app
    #command: sh -c "npm install && npx lerna run server:build && npx lerna run server:start"
    command: sh -c "npm install && npx lerna run server:start:dev"
    working_dir: /app
    volumes:
      - ../:/app
    restart: unless-stopped

  postgres:
    image: postgres:15
    ports:
      - "5404:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/repid
    networks:
      - app
    volumes:
      - ../../../database/:/var/lib/postgresql/data
    restart: unless-stopped
